// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkxkyghudjjwzgtyaywa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5reGt5Z2h1ZGpqd3pndHlheXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDAyNjQsImV4cCI6MjA1NzY3NjI2NH0.UH_tE8E9UvxI2AeAoxCK93t9bTgd7m9_SxUeN2WGIJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);